<?php

use Drupal\Component\Utility\Html;
/**
 * Implements hook_mail().
 * 
 * 
 */
function d8campaign_mail($key, &$message, $params) {
    $body = $params['template'];
    $subject = $params['subject'];

    switch ($key) {
      case 'SVCCampaign_signature':
        $message['headers']['MIME-Version'] = "1.0";
        $message['headers']['Content-Type'] = "text/html; charset=UTF-8";
        $message['subject'] = $subject;
        $message['body'][] = Html::escape($body);
        break;
    }
}

/**
 * Implements hook_theme().
 * 
 * Register a module or theme's theme implementations.
 * The implementations declared by this hook specify how a particular render array is to be rendered as HTML.
 * 
 * See: https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21theme.api.php/function/hook_theme/8.2.x
 * 
 * If you change this method, clear theme registry and routing table 'drush cc theme-registry' and 'drush cc router'.
 */
function d8campaign_theme($existing, $type, $theme, $path) {

  return [		
    // Name of the theme hook. This is used in the controller to trigger the hook.
    'signature_account_overview' => [
      'render element' => 'children',
      // If no template name is defined here, it defaults to the name of the theme hook, ie. module-name-theme-hook.html.twig
      'template' => 'signature-account-overview',
      // Optionally define path to Twig template files. Defaults to the module's ./templates/ directory.
      'path' => $path . '/templates',
      // Optionally define variables that will be passed to the Twig template and set default values for them.
      'variables' => [
        'variable1' => NULL,
        'variable2' => NULL,
        'variable3' => NULL,
        'is_accepted' => NULL,
      ],
    ],
    'testcampaign_account_overview' => [
      'render element' => 'children',
      // If no template name is defined here, it defaults to the name of the theme hook, ie. module-name-theme-hook.html.twig
      'template' => 'testcampaign-account-overview',
      // Optionally define path to Twig template files. Defaults to the module's ./templates/ directory.
      'path' => $path . '/templates',
      // Optionally define variables that will be passed to the Twig template and set default values for them.
      'variables' => [
        'variable1' => NULL,
        'variable2' => NULL,
        'variable3' => NULL,
        'is_accepted' => NULL,
      ],
    ],
    'already_submitted' => [
      'render element' => 'children',
      'template' => 'already-submitted',
      'path' => $path . '/templates',
      'variables' => [
        'type' => NULL,
      ],
    ],
  ];

}

/**
 * 
 * create hook_page_attachments(array $page).
 */
function d8campaign_page_attachments(array &$attachments){
  $attachments['#attached']['library'][] = 'd8campaign/d8campaign-styling';
}